/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BackGrounds.Lienzo;
import BackGrounds.Resolucion;
import Characthers.Enemy;
import Characthers.Steve;
import Powers.StevePower;
import Sounds.BackSound;
import java.applet.AudioClip;
import java.awt.Cursor;

/**
 *
 * @author estudiantes
 */
public class Principal extends javax.swing.JFrame implements Resolucion {
    
    Steve steve;
    Lienzo lienzo;
    Enemy enemy;
    StevePower powa;
    private int WIDTH = ancho;
    private int HEIGHT = alto+(alto/15);
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Cursor cursor = new Cursor(1);
        setCursor(cursor);
        setTitle("Steve Hunt");
        steve = new Steve();
        steve.setActual(steve.getSkey(1));//poner imagen (setactual - tecla oprimida)
        steve.setX(1000);
        steve.setY(700);
        powa = new StevePower(2000,2000);
        powa.llenar();
        enemy = new Enemy();
        lienzo  = new Lienzo(steve,powa);
        setLayout(null);
        add(lienzo);
        addMouseListener(lienzo);
        addMouseMotionListener(lienzo);
        addKeyListener(lienzo);
        pack();
        setBounds(0, 0, WIDTH, HEIGHT);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
