/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animation;

import java.util.ArrayList;

/**
 *
 * @author Braya
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
     public void Adelante()
    {
         
       
       
    }
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/s1.png"))); // NOI18N
        fondo.setText("jLabel1");

        boton.setText("jButton1");
        boton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addComponent(boton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonKeyPressed
        // TODO add your handling code here:
        int x = fondo.getX();
        int y = fondo.getY();
        ArrayList<String> adelante = new ArrayList();
         adelante.add("/imagenes/s1.png");
         adelante.add("/imagenes/s2.png");
         adelante.add("/imagenes/s3.png");
         adelante.add("/imagenes/s4.png");  
         adelante.add("/imagenes/s5.png");
         adelante.add("/imagenes/s6.png");
         adelante.add("/imagenes/s7.png");
         adelante.add("/imagenes/s8.png");  
         adelante.add("/imagenes/s9.png");
       ArrayList<String> atras = new ArrayList();
         atras.add("/imagenes/w1.png");
         atras.add("/imagenes/w2.png");
         atras.add("/imagenes/w3.png");
         atras.add("/imagenes/w4.png");  
         atras.add("/imagenes/w5.png");
         atras.add("/imagenes/w6.png");
         atras.add("/imagenes/w7.png");
         atras.add("/imagenes/w8.png");  
         atras.add("/imagenes/w9.png");
       ArrayList<String> izquierda = new ArrayList();
         izquierda.add("/imagenes/a1.png");
         izquierda.add("/imagenes/a2.png");
         izquierda.add("/imagenes/a3.png");
         izquierda.add("/imagenes/a4.png");  
         izquierda.add("/imagenes/a5.png");
         izquierda.add("/imagenes/a6.png");
         izquierda.add("/imagenes/a7.png");
         izquierda.add("/imagenes/a8.png");  
         izquierda.add("/imagenes/a9.png");
       ArrayList<String> derecha = new ArrayList();
        derecha.add("/imagenes/d1.png");
        derecha.add("/imagenes/d2.png");
        derecha.add("/imagenes/d3.png");
        derecha.add("/imagenes/d4.png");  
        derecha.add("/imagenes/d5.png");
        derecha.add("/imagenes/d6.png");
        derecha.add("/imagenes/d7.png");
        derecha.add("/imagenes/d8.png");  
        derecha.add("/imagenes/d9.png");
        switch(evt.getKeyChar())
        {
            case 'w':
                y=y-3;
                fondo.setLocation(x,y);
                fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource(atras.get(i.getI())))); 
                i.setContador(i.getContador()+1);
                i.Cambio((atras.size()-1));
                break;
                case 's':
                y=y+3;
                fondo.setLocation(x,y);
                fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource(adelante.get(i.getI())))); 
                i.setContador(i.getContador()+1);
                i.Cambio((adelante.size()-1));
                if(i.Parpadear() ==true)
                {
                   fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/s10.png"))); 
                }
                break;
                case 'a':
                x=x-3;
                fondo.setLocation(x,y);
                fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource(izquierda.get(i.getI())))); 
                i.setContador(i.getContador()+1);
                i.Cambio((izquierda.size()-1));
                if(i.Parpadear() ==true)
                {
                   fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.png"))); 
                }
                break;
                case 'd':
                x=x+3;
                fondo.setLocation(x,y);
                fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource(derecha.get(i.getI())))); 
                i.setContador(i.getContador()+1);
                i.Cambio((izquierda.size()-1));
                if(i.Parpadear() ==true)
                {
                   fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.png"))); 
                }
                break;
        }
        
    }//GEN-LAST:event_botonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    Change i =new Change();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
